/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LeapYear;

public class App {
    
    public static void main(String[] args) {
        System.out.print("Printing leap years from 1900 to 2001");
        LeapYearOracle lyo = new LeapYearOracle();
        for(int yyy=1900; yyy<2001; yyy++){
            if(lyo.isLeap(yyy)){
                System.out.print(yyy);
            }
        }
    }
}
