/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LeapYear;

import org.junit.Test;
import static org.junit.Assert.*;

public class LeapYearOracleTest {

    void baseTest(int inputYear, boolean expectedOutput){
        LeapYearOracle lyo = new LeapYearOracle();
        assertEquals(expectedOutput, lyo.isLeap(inputYear));
    }

    @Test public void testCommonYear() {
        baseTest(2001, false);
    }
    @Test public void testLeapYear() {
        baseTest(1904, true);
    }
    @Test public void testAtypicalCommonYear() {
        baseTest(1900, false);
    }
    @Test public void testAtypicalLeapYear() {
        baseTest(2000, true);
    }
}
